spring:
  datasource:
    url: jdbc:mysql://b212879e042b97:f5b20f86@us-cdbr-iron-east-04.cleardb.net/heroku_1c3ebfe4d06dc45?reconnect=true
    username: b212879e042b97
    password: f5b20f86
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true