spring:
  datasource:
    url: jdbc:mysql://bdc5183b78a0ce:b3539375@us-cdbr-iron-east-04.cleardb.net/heroku_d5ec1eac00defae?reconnect=true
    username: bdc5183b78a0ce
    password: b3539375
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true