spring:
  datasource:
    url: jdbc:mysql://bh8j7du4pfiv5hv1:utnd8qxxjbvv9b4n@gk90usy5ik2otcvi.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/mu69x1562g507dgc
    username: bh8j7du4pfiv5hv1
    password: utnd8qxxjbvv9b4n
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true