spring:
  datasource:
    url: jdbc:mysql://bec3c866a045fc:0fffef5f@eu-cdbr-west-02.cleardb.net/heroku_16e2145f33ab0ff?reconnect=true
    username: bec3c866a045fc
    password: 0fffef5f
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false