spring:
  datasource:
    url: jdbc:mysql://localhost:3306/osh_dev
    username: osh_dev_user
    password: gwassy
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true