spring:
  datasource:
    url: jdbc:mysql://b69nzy4hp47o6cit:o05jqdasr3ndjtds@gk90usy5ik2otcvi.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/n7s62of1ecrdeu7z
#    username: osh_dev_user
#    password: gwassy
    username: b69nzy4hp47o6cit
    password: o05jqdasr3ndjtds
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: osh_database_create.sql